// ==========================================
// 3. TARJIMA (O'zgarmadi)
// ==========================================
import 'package:turon_beton/core/app_state.dart';

const Map<String, Map<String, String>> tr = {
  'uz_lat': {
    'login': 'Kirish',
    'register': 'Ro\'yxatdan o\'tish',
    'name': 'Ism familiya',
    'phone': 'Telefon raqam',
    'address': 'Yashash manzili',
    'pass': 'Parol',
    'pass2': 'Parolni tasdiqlang',
    'login_btn': 'Tizimga kirish',
    'reg_btn': 'Ro\'yxatdan o\'tish',
    'have_acc': 'Akkauntingiz bormi? Kirish ↗',
    'no_acc': 'Yangi akkaunt yaratish ↗',
    'home': 'Asosiy',
    'catalog': 'Katalog',
    'masters': 'Ustalar',
    'profile': 'Profil',
    'cart': 'Savatcha',
    'admin': 'Admin',
    'history': 'Tarix',
    'lang': 'Tilni o\'zgartirish',
    'contact': 'Aloqa',
    'settings': 'Sozlamalar',
    'dark_mode': 'Tungi rejim',
    'role_client': 'Men Xaridorman',
    'role_master': 'Men Ustaman',
    'edit_prof': 'Profil tahriri',
    'payments': 'To\'lov qilish',
    'add': 'Savatga',
    'total': 'Jami:',
    'checkout': 'To\'lovga o\'tish',
    'empty': 'Savatcha bo\'sh',
    'popular': 'Ommabop mahsulotlar',
    'all': 'Barchasi >',
    'choose_prof': 'Kasbingizni tanlang',
    'find_masters': 'Malakali ustalar xizmati',
    'find_masters_sub': 'O\'z ishingiz ustalarini toping',
    'prod_plita': 'Plita PK',
    'prod_beton': 'Tayyor Beton',
    'prod_kolodes': 'Kolodes',
    'prod_blok': 'Fundament Blok',
    'prod_stolba': 'Beton Stolba',
    'prod_qopqoq': 'Qopqoq',
    'prod_lyuk': 'Qopqoq Lyukli',
    'promo_title': 'TEZ KUNDA!',
    'promo_sub': 'Super mustahkam M400 markali betonlarimiz.',
    'calc_title': 'Aqlli Hisoblagich',
    'len_meter': 'Uzunligi (metr):',
    'wire_count': 'Simlar soni:',
    'qty_pieces': 'Nechta kerak:',
    'price_per_piece': '1 dona narxi:',
    'total_sum': 'Jami summa:',
    'add_to_cart': 'Savatga qo\'shish',
    'enter_length': 'Masalan: 4.70',
    'wire_text': 'talik sim',
    'm_santexnik': 'Santexnik',
    'm_gisht': 'G\'isht teruvchi',
    'm_elektrik': 'Elektrik',
    'm_qum': 'Qumshuvoqchi',
    'm_payvand': 'Payvandchi',
    'm_tom': 'Tom yopuvchi',
    'm_boyoq': 'Bo\'yoqchi',
    'm_kafel': 'Kafelchi',
    'm_duradgor': 'Duradgor',
    'm_betonchi': 'Betonchi',
    'no_masters': 'Hozircha bu yo\'nalishda ustalar yo\'q',
    'masters_count': 'ta usta',
    'splash_sub': 'Qurilish Eko-tizimi',
    'status_pending': 'KUTILMOQDA...',
    'status_process': 'JARAYONDA',
    'status_delivery': 'YETKAZIB BORILMOQDA',
    'pay_method': 'To\'lov tizimini tanlang',
    'pay_processing': 'To\'lov tekshirilmoqda...',
    'pay_success': 'To\'lov muvaffaqiyatli! Buyurtma zavodga yuborildi.',
    'config_error': 'Xatolik: Konfiguratsiya to\'liq emas!',
    'phone_error': 'Telefon raqami noto\'g\'ri!',
    'password_short': 'Parol 8 ta belgidan kam!',
    'password_match': 'Parollar mos kelmadi!',
    'fill_fields': 'Barcha maydonlarni to\'ldiring!',
    'welcome_back': 'Xush kelibsiz!',
    'create_account': 'Hisob yaratish',
  },
  'uz_cyr': {
    'login': 'Кириш',
    'register': 'Рўйхатдан ўтиш',
    'name': 'Исм фамилия',
    'phone': 'Телефон рақам',
    'address': 'Манзил',
    'pass': 'Парол',
    'pass2': 'Паролни тасдиқланг',
    'login_btn': 'Тизимга кириш',
    'reg_btn': 'Рўйхатдан ўтиш',
    'have_acc': 'Аккаунтингиз борми? Кириш ↗',
    'no_acc': 'Янги аккаунт яратиш ↗',
    'home': 'Асосий',
    'catalog': 'Каталог',
    'masters': 'Усталар',
    'profile': 'Профил',
    'cart': 'Саватча',
    'admin': 'Админ',
    'history': 'Тарих',
    'lang': 'Тилни ўзгартириш',
    'contact': 'Алоқа',
    'settings': 'Созламалар',
    'dark_mode': 'Тунги режим',
    'role_client': 'Мен Харидорман',
    'role_master': 'Мен Устаман',
    'edit_prof': 'Профил таҳрири',
    'payments': 'Тўлов қилиш',
    'add': 'Саватга',
    'total': 'Жами:',
    'checkout': 'Тўловга ўтиш',
    'empty': 'Саватча бўш',
    'popular': 'Оммабоп маҳсулотлар',
    'all': 'Барчаси >',
    'choose_prof': 'Касбингизни танланг',
    'find_masters': 'Малакали усталар хизмати',
    'find_masters_sub': 'Ўз ишингиз усталарини топинг',
    'prod_plita': 'Плита ПК',
    'prod_beton': 'Тайёр Бетон',
    'prod_kolodes': 'Колодес',
    'prod_blok': 'Фундамент Блок',
    'prod_stolba': 'Бетон Столба',
    'prod_qopqoq': 'Қопқоқ',
    'prod_lyuk': 'Қопқоқ Люкли',
    'promo_title': 'ТЕЗ КУНДА!',
    'promo_sub': 'Супер мустаҳкам М400 маркали бетонларимиз.',
    'calc_title': 'Ақлли Ҳисоблагич',
    'len_meter': 'Узунлиги (метр):',
    'wire_count': 'Симлар сони:',
    'qty_pieces': 'Нечта керак:',
    'price_per_piece': '1 дона нархи:',
    'total_sum': 'Жами сумма:',
    'add_to_cart': 'Саватга қўшиш',
    'enter_length': 'Масалан: 4.70',
    'wire_text': 'талик сим',
    'm_santexnik': 'Сантехник',
    'm_gisht': 'Ғишт терувчи',
    'm_elektrik': 'Электрик',
    'm_qum': 'Қумшувоқчи',
    'm_payvand': 'Пайвандчи',
    'm_tom': 'Том ёпувчи',
    'm_boyoq': 'Бўёқчи',
    'm_kafel': 'Кафельчи',
    'm_duradgor': 'Дурадгор',
    'm_betonchi': 'Бетончи',
    'no_masters': 'Ҳозирча бу йўналишда усталар йўқ',
    'masters_count': 'та уста',
    'splash_sub': 'Қурилиш Эко-тизими',
    'status_pending': 'КУТИЛМОҚДА...',
    'status_process': 'ЖАРАЁНДА',
    'status_delivery': 'ЕТКАЗИБ БОРИЛМОҚДА',
    'pay_method': 'Тўлов тизимини танланг',
    'pay_processing': 'Тўлов текширилмоқда...',
    'pay_success': 'Тўлов муваффақиятли! Буюртма заводга юборилди.',
    'config_error': 'Хатолик: Конфигурация тўлиқ эмас!',
    'phone_error': 'Телефон рақами нотўғри!',
    'password_short': 'Парол 8 та белгидан кам!',
    'password_match': 'Пароллар мос келмади!',
    'fill_fields': 'Барча майдонларни тўлдиринг!',
    'welcome_back': 'Хуш келибсиз!',
    'create_account': 'Ҳисоб яратиш',
  },
  'ru': {
    'login': 'Войти',
    'register': 'Регистрация',
    'name': 'Имя',
    'phone': 'Телефон',
    'address': 'Адрес',
    'pass': 'Пароль',
    'pass2': 'Повторите пароль',
    'login_btn': 'Войти',
    'reg_btn': 'Зарегистрироваться',
    'have_acc': 'Уже есть аккаунт? Войти ↗',
    'no_acc': 'Создать аккаунт ↗',
    'home': 'Главная',
    'catalog': 'Каталог',
    'masters': 'Мастера',
    'profile': 'Профиль',
    'cart': 'Корзина',
    'admin': 'Админ',
    'history': 'История',
    'lang': 'Язык',
    'contact': 'Связь',
    'settings': 'Настройки',
    'dark_mode': 'Ночной режим',
    'role_client': 'Покупатель',
    'role_master': 'Мастер',
    'edit_prof': 'Изменить',
    'payments': 'Оплата',
    'add': 'В корзину',
    'total': 'Итого:',
    'checkout': 'Перейти к оплате',
    'empty': 'Корзина пуста',
    'popular': 'Популярные товары',
    'all': 'Все >',
    'choose_prof': 'Выберите профессию',
    'find_masters': 'Услуги мастеров',
    'find_masters_sub': 'Найдите лучших мастеров своего дела',
    'prod_plita': 'Плита ПК',
    'prod_beton': 'Товарный Бетон',
    'prod_kolodes': 'Колодец',
    'prod_blok': 'Фундаментный Блок',
    'prod_stolba': 'Бетонный Столб',
    'prod_qopqoq': 'Крышка',
    'prod_lyuk': 'Крышка с Люком',
    'promo_title': 'СКОРО!',
    'promo_sub': 'Супер прочный бетон марки М400.',
    'calc_title': 'Умный Калькулятор',
    'len_meter': 'Длина (метр):',
    'wire_count': 'Кол-во струн:',
    'qty_pieces': 'Кол-во:',
    'price_per_piece': 'Цена за 1 шт:',
    'total_sum': 'Итоговая сумма:',
    'add_to_cart': 'Добавить в корзину',
    'enter_length': 'Например: 4.70',
    'wire_text': 'струн',
    'm_santexnik': 'Сантехник',
    'm_gisht': 'Каменщик',
    'm_elektrik': 'Электрик',
    'm_qum': 'Штукатур',
    'm_payvand': 'Сварщик',
    'm_tom': 'Кровельщик',
    'm_boyoq': 'Маляр',
    'm_kafel': 'Плиточник',
    'm_duradgor': 'Плотник',
    'm_betonchi': 'Бетонщик',
    'no_masters': 'Пока нет мастеров',
    'masters_count': 'мастеров',
    'splash_sub': 'Строительная Эко-система',
    'status_pending': 'ОЖИДАЕТСЯ...',
    'status_process': 'В ПРОЦЕССЕ',
    'status_delivery': 'ДОСТАВЛЯЕТСЯ',
    'pay_method': 'Выберите способ оплаты',
    'pay_processing': 'Проверка оплаты...',
    'pay_success': 'Оплата прошла успешно! Заказ отправлен на завод.',
    'config_error': 'Ошибка: Конфигурация неполная!',
    'phone_error': 'Неверный номер телефона!',
    'password_short': 'Пароль менее 8 символов!',
    'password_match': 'Пароли не совпадают!',
    'fill_fields': 'Заполните все поля!',
    'welcome_back': 'С возвращением!',
    'create_account': 'Создать аккаунт',
  }
};

String t(dynamic key, {String? lang}) {
  if (key == null) return '';
  final currentLang = lang ?? AppState.currentLang;
  return tr[currentLang]?[key.toString()] ?? key.toString();
}
